name: Terraform CI/CD

on:
  push:
    branches:
      - main
      - feature/**
  pull_request:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: parent

    steps:
      # 1. Checkout code
      - name: Checkout Code
        uses: actions/checkout@v4

      # 2. Azure Login using OIDC
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: "613a3d26-f18c-46b4-9f29-dbcae1b8a227"
          tenant-id: "39faf049-c790-4cc2-9968-b71d24fbf612"
          subscription-id: "8e63d43f-1267-43f8-99a8-1132205c4cb0"

      # 3. Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # 4. Terraform Init
      - name: Terraform Init
        run: terraform init

      # 5. Terraform Validate
      - name: Terraform Validate
        run: terraform validate

      # 6. Terraform Plan
      - name: Terraform Plan
        run: terraform plan

      # 7. Terraform Apply - ONLY MAIN
      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve
